apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
spec:
  replicas: 2  # High availability
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
      - name: employee-app
        image: employee-app:${BUILD_ID}  # Dynamic tag from Jenkins
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: employee-app-service
spec:
  selector:
    app: employee-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Or ClusterIP for internal access